name: line message
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}
      - name: send default message
        uses: louis70109/line-notify-action@master
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: |
            ${{ github.event.head_commit.message }}